// order-frontend/order-react/src/orders/order-list/order-list.tsx
import { useEffect, useState } from 'react'
import './order-list.css'
import type { Order } from '../../models/Order';
import { getOrdersAction } from '../actions/get-orders.action';
import { useAuthStore } from '../../login/store/auth.store';
import { useNavigate } from 'react-router-dom';
import { useOrderStore } from '../store/order.store';
import { ModalOrder } from '../order-modal/modal-order';
import { deleteOrderAction } from '../actions/delete-order.action';


export const OrderList = () => {

    const { isAuthenticated, setIsAuthenticated } = useAuthStore();
    const { orders, setOrders } = useOrderStore();
    const [id, setId] = useState<number | undefined>(undefined);
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [isLoading, setIsLoading] = useState(true);
    const navigate = useNavigate();

    const handleLogout = () => {
        sessionStorage.removeItem('credentials');
        sessionStorage.removeItem('username');
        setIsAuthenticated(false);
        navigate('/login');
    }

    const navigateToOrderDetails = (_orderId: number) => {
        navigate(`/details/${_orderId}`);
    }

    const calculateTotal = (order: Order): number => {
        return order.items.reduce((total, item) => total + (item.quantity * item.unitPrice), 0);
    }

    const openCreateModal = (orderId?: number, event?: React.MouseEvent) => {
        event?.stopPropagation();
        setId(orderId);
        setIsModalOpen(true);
    }

    const deleteOrder = (orderId: number, event?: React.MouseEvent) => {
        event?.stopPropagation();
        setIsLoading(true);
        deleteOrderAction(orderId).then(() => {
            const updatedOrders = orders.filter((order: Order) => order.id !== orderId);
            setOrders(updatedOrders);
            setIsLoading(false);
        });
    }

    useEffect(() => {
        if (!isAuthenticated) {
            navigate('/login');
            return;
        }
        getOrdersAction().then((orders) => {
            setOrders(orders);
            setIsLoading(false);
        });
    }, [isAuthenticated]);

    return (
        <div className="order-list-container">
            <header className="header">
                <div className="header-content">
                    <h1>Lista de Pedidos</h1>
                    <div className="header-actions">
                        <button className="new-order-button" onClick={() => openCreateModal(undefined)}>
                            <i className="fa fa-plus"></i> Nuevo Pedido
                        </button>
                        <div className="stream-indicator">
                            <span className="stream-dot"></span>
                            <span>Conectado en tiempo real</span>
                        </div>

                        <div className="user-info">
                            <span className="stream-indicator">Usuario: {sessionStorage.getItem('username')} </span>
                            <button className="logout-button" onClick={handleLogout}>Cerrar Sesión</button>
                        </div>
                    </div>
                </div>
            </header>


            {isLoading && (
                <div className="loading">
                    <p>Cargando pedidos...</p>
                </div>
            )}

            <div className="orders-grid">
                {orders.length > 0 ? (
                    orders.map((order: Order) => (
                        <div className="order-card" onClick={() => navigateToOrderDetails(order.id)} key={order.id}>
                            <div className='card-actions'>
                                <button className="icon-btn edit-btn" onClick={(event) => openCreateModal(order.id, event)} title="Editar">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                                        <path
                                            d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                                    </svg>
                                </button>
                                <button className="icon-btn delete-btn" onClick={(event) => deleteOrder(order.id, event)} title="Eliminar">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                                        <path
                                            d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z" />
                                        <path
                                            d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z" />
                                    </svg>
                                </button>
                            </div>
                            <div className="order-header">
                                <h2>Pedido #{order.id}</h2>
                                <span className="order-date">{order.createdAt}</span>
                            </div>
                            <div className="order-customer">
                                <strong>Cliente:</strong> {order.customerName}
                            </div>
                            <div className="order-items">
                                <strong>Items:</strong> {order.items.length}
                            </div>
                            <div className="order-total">
                                <strong>Total:</strong> {calculateTotal(order)}
                            </div>
                        </div>
                    ))
                ) : (
                    <div className="empty">
                        <p>No hay pedidos disponibles</p>
                    </div>
                )
                }
            </div>

            <div className="error">
                <p></p>
                <button>Reintentar</button>
            </div>

            {isModalOpen && (
                <ModalOrder onClose={() => setIsModalOpen(false)} id={id} />
            )}

        </div>

    )
}

export default OrderList;

// order-frontend/order-angular/src/app/components/order-list/order-list.component.ts
import { Component, signal, inject, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { OrderService } from '../../services/order.service';
import { AuthService } from '../../services/auth.service';
import { Order } from '../../models/Order';
import { Subscription } from 'rxjs';
import { ModalComponent } from '../modal/modal.component';
import { FormBuilder, FormGroup, FormArray, Validators, ReactiveFormsModule, FormsModule } from '@angular/forms';
import { CreateOrderRequest } from '../../models/CreateOrderRequest';
import { UpdateOrderRequest } from '../../models/UpdateOrderRequest';



@Component({
  selector: 'app-order-list',
  standalone: true,
  imports: [CommonModule, RouterModule, ModalComponent, ReactiveFormsModule, FormsModule],
  templateUrl: './order-list.component.html',
  styleUrl: './order-list.component.css'
})
export class OrderListComponent implements OnDestroy {
  private orderService = inject(OrderService);

  private authService = inject(AuthService);
  private fb = inject(FormBuilder);

  private streamSubscription?: Subscription;
  private reconnectTimeout?: ReturnType<typeof setTimeout>;
  private isDestroyed = false;
  private retryCount = 0;
  private readonly maxRetries = 5;

  // Signals 
  orders = signal<Order[]>([]);
  loading = signal<boolean>(true);
  error = signal<string | null>(null);
  isStreaming = signal<boolean>(false);

  isModalOpen = signal<boolean>(false);
  modalMode = signal<'create' | 'edit' | 'delete'>('create');
  selectedOrder = signal<Order | null>(null);
  orderForm: FormGroup;

  constructor() {
    this.orderForm = this.fb.group({
      customerName: ['', [Validators.required, Validators.minLength(3)]],
      items: this.fb.array([])
    });

    this.loadOrders();
    this.connectToStream();
  }

  get items(): FormArray {
    return this.orderForm.get('items') as FormArray;
  }

  addItem(): void {
    const itemGroup = this.fb.group({
      sku: ['', Validators.required],
      description: ['', Validators.required],
      quantity: [1, [Validators.required, Validators.min(1)]],
      unitPrice: [0, [Validators.required, Validators.min(0.01)]]
    });
    this.items.push(itemGroup);
  }

  removeItem(index: number): void {
    this.items.removeAt(index);
  }

  openCreateModal(): void {
    this.modalMode.set('create');
    this.orderForm.reset();
    this.items.clear();
    this.addItem(); // Add one initial item
    this.isModalOpen.set(true);
  }

  openEditModal(order: Order, event?: Event): void {
    if (event) {
      event.preventDefault();
      event.stopPropagation();
    }
    this.modalMode.set('edit');
    this.selectedOrder.set(order);

    // Reset form
    this.orderForm.reset();
    this.items.clear();

    // Patch Values
    this.orderForm.patchValue({
      customerName: order.customerName
    });

    // Re-create items form array
    order.items.forEach(item => {
      const itemGroup = this.fb.group({
        sku: [item.sku, Validators.required],
        description: [item.description, Validators.required],
        quantity: [item.quantity, [Validators.required, Validators.min(1)]],
        unitPrice: [item.unitPrice, [Validators.required, Validators.min(0.01)]]
      });
      this.items.push(itemGroup);
    });

    this.isModalOpen.set(true);
  }

  openDeleteModal(order: Order, event?: Event): void {
    if (event) {
      event.preventDefault();
      event.stopPropagation();
    }
    this.modalMode.set('delete');
    this.selectedOrder.set(order);
    this.isModalOpen.set(true);
  }

  closeModal(): void {
    this.isModalOpen.set(false);
    this.selectedOrder.set(null);
  }

  submitOrder(): void {
    if (this.orderForm.invalid) {
      this.orderForm.markAllAsTouched();
      return;
    }

    const formValue = this.orderForm.value;
    const mode = this.modalMode();

    if (mode === 'create') {
      const request: CreateOrderRequest = {
        customerName: formValue.customerName,
        items: formValue.items
      };

      this.loading.set(true);
      this.orderService.createOrder(request).subscribe({
        next: (newOrder) => {
          this.orders.update(orders => [...orders, newOrder]);
          this.loading.set(false);
          this.closeModal();
        },
        error: (err) => {
          console.error('Error creating order:', err);
          this.error.set('Failed to create order');
          this.loading.set(false);
        }
      });
    } else if (mode === 'edit') {
      const orderId = this.selectedOrder()?.id;
      if (!orderId) return;

      const request: UpdateOrderRequest = {
        customerName: formValue.customerName,
        items: formValue.items
      };

      this.loading.set(true);
      this.orderService.updateOrder(orderId, request).subscribe({
        next: (updatedOrder) => {
          this.orders.update(orders =>
            orders.map(o => o.id === updatedOrder.id ? updatedOrder : o)
          );
          this.loading.set(false);
          this.closeModal();
        },
        error: (err) => {
          console.error('Error updating order:', err);
          this.error.set('Failed to update order');
          this.loading.set(false);
        }
      });
    }
  }

  confirmDelete(): void {
    const order = this.selectedOrder();
    if (!order) return;

    this.loading.set(true);
    this.orderService.deleteOrder(order.id).subscribe({
      next: () => {
        this.orders.update(orders => orders.filter(o => o.id !== order.id));
        this.loading.set(false);
        this.closeModal();
      },
      error: (err) => {
        console.error('Error deleting order:', err);
        this.error.set('Failed to delete order');
        this.loading.set(false);
      }
    });
  }

  ngOnDestroy(): void {
    this.isDestroyed = true;
    if (this.reconnectTimeout) {
      clearTimeout(this.reconnectTimeout);
    }
    this.disconnectFromStream();
  }

  loadOrders(): void {
    this.loading.set(true);
    this.error.set(null);

    this.orderService.getAllOrders().subscribe({
      next: (orders) => {
        this.orders.set(orders);
        this.loading.set(false);
      },
      error: (err) => {
        this.error.set('Error al cargar los pedidos');
        this.loading.set(false);
        console.error('Error loading orders:', err);
      }
    });
  }

  connectToStream(): void {
    this.isStreaming.set(true);
    this.streamSubscription = this.orderService.streamOrders().subscribe({
      next: (orders) => {
        this.orders.set(orders);
        this.loading.set(false);
        this.error.set(null);
        // Reset retry count on successful connection
        this.retryCount = 0;
      },
      error: (err) => {
        this.isStreaming.set(false);
        console.error('Stream error:', err);

        // Only retry if we haven't exceeded max retries
        if (this.retryCount < this.maxRetries && !this.isDestroyed) {
          this.retryCount++;
          this.error.set(`Error en la conexión en tiempo real (Intento ${this.retryCount}/${this.maxRetries})`);

          this.reconnectTimeout = setTimeout(() => {
            if (!this.isDestroyed) {
              this.connectToStream();
            }
          }, 5000);
        } else {
          // Max retries reached
          this.error.set('Error en la conexión en tiempo real. Se agotaron los intentos de reconexión.');
          this.isStreaming.set(false);
        }
      }
    });
  }

  disconnectFromStream(): void {
    if (this.streamSubscription) {
      this.streamSubscription.unsubscribe();
      this.isStreaming.set(false);
    }
  }

  formatDate(dateString: string): string {
    return new Date(dateString).toLocaleString('es-ES');
  }

  calculateTotal(order: Order): number {
    return order.items.reduce((total, item) => total + (item.quantity * item.unitPrice), 0);
  }

  logout(): void {
    this.authService.logout();
  }

  getUsername(): string | null {
    return this.authService.username();
  }

  // Public handlers for HTML that can also handle event stopping
  editOrder(order: Order, event?: Event): void {
    this.openEditModal(order, event);
  }

  deleteOrder(order: Order, event?: Event): void {
    this.openDeleteModal(order, event);
  }

}


<div class="order-list-container">
  <header class="header">
    <div class="header-content">
      <h1>Lista de Pedidos</h1>
      <div class="header-actions">
        <!-- New Create Order Button -->
        <button class="create-button" (click)="openCreateModal()">
          <i class="fa fa-plus"></i> Nuevo Pedido
        </button>

        @if (isStreaming()) {
        <div class="stream-indicator">
          <span class="stream-dot"></span>
          <span>Conectado en tiempo real</span>
        </div>
        }
        @if (getUsername()) {
        <div class="user-info">
          <span>Usuario: {{ getUsername() }}</span>
          <button class="logout-button" (click)="logout()">Cerrar Sesión</button>
        </div>
        }
      </div>
    </div>
  </header>

  @if (loading() && !isModalOpen()) {
  <div class="loading">
    <p>Cargando pedidos...</p>
  </div>
  } @else if (error() && !isModalOpen()) {
  <div class="error">
    <p>{{ error() }}</p>
    <button (click)="loadOrders()">Reintentar</button>
  </div>
  } @else if (orders().length === 0) {
  <div class="empty">
    <p>No hay pedidos disponibles</p>
    <button class="btn-primary" (click)="openCreateModal()">Crear primer pedido</button>
  </div>
  } @else {
  <div class="orders-grid">
    @for (order of orders(); track order.id) {
    <a [routerLink]="['/orders', order.id]" class="order-card">
      <div class="card-actions">
        <button class="icon-btn edit-btn" (click)="editOrder(order, $event)" title="Editar">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
            <path
              d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
          </svg>
        </button>
        <button class="icon-btn delete-btn" (click)="deleteOrder(order, $event)" title="Eliminar">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
            <path
              d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z" />
            <path
              d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z" />
          </svg>
        </button>
      </div>
      <div class="order-header">
        <h2>Pedido #{{ order.id }}</h2>
        <span class="order-date">{{ formatDate(order.createdAt) }}</span>
      </div>
      <div class="order-customer">
        <strong>Cliente:</strong> {{ order.customerName }}
      </div>
      <div class="order-items">
        <strong>Items:</strong> {{ order.items.length }}
      </div>
      <div class="order-total">
        <strong>Total:</strong> {{ calculateTotal(order) | number:'1.2-2' }} $
      </div>
    </a>
    }
  </div>
  }
</div>

<app-modal [isOpen]="isModalOpen()"
  [title]="modalMode() === 'create' ? 'Crear Nuevo Pedido' : modalMode() === 'edit' ? 'Editar Pedido' : 'Confirmar Eliminación'"
  (close)="closeModal()">
  @if (modalMode() === 'create' || modalMode() === 'edit') {
  <form [formGroup]="orderForm" (ngSubmit)="submitOrder()" class="create-order-form">
    <div class="form-section">
      <label for="customerName" class="form-label">Nombre del Cliente</label>
      <input id="customerName" type="text" formControlName="customerName" class="form-input"
        placeholder="Ej: Juan Pérez"
        [class.invalid]="orderForm.get('customerName')?.invalid && orderForm.get('customerName')?.touched">
      @if (orderForm.get('customerName')?.invalid && orderForm.get('customerName')?.touched) {
      <span class="error-msg">El nombre es requerido (mínimo 3 caracteres)</span>
      }
    </div>

    <div class="items-header">
      <h3>Items</h3>
      <button type="button" class="btn-text" (click)="addItem()">+ Agregar Item</button>
    </div>

    <div formArrayName="items" class="items-list">
      @for (item of items.controls; track i; let i = $index) {
      <div [formGroupName]="i" class="item-row">
        <div class="form-group small">
          <input formControlName="sku" placeholder="SKU" class="form-input">
        </div>
        <div class="form-group medium">
          <input formControlName="description" placeholder="Descripción" class="form-input">
        </div>
        <div class="form-group tiny">
          <input type="number" formControlName="quantity" placeholder="Cant." class="form-input" min="1">
        </div>
        <div class="form-group small">
          <input type="number" formControlName="unitPrice" placeholder="Precio" class="form-input" min="0" step="0.01">
        </div>
        @if (items.length > 1) {
        <button type="button" class="btn-icon-danger" (click)="removeItem(i)" title="Eliminar item">&times;</button>
        }
      </div>
      }
    </div>

    <div class="modal-actions end">
      <button type="button" class="btn-secondary" (click)="closeModal()">Cancelar</button>
      <button type="submit" class="btn-primary" [disabled]="orderForm.invalid || loading()">
        @if (loading()) { Guardando... } @else {
        @if (modalMode() === 'create') { Crear Pedido } @else { Actualizar Pedido }
        }
      </button>
    </div>
  </form>
  } @else {
  <div class="delete-confirmation">
    <p>¿Estás seguro de que deseas eliminar el pedido <strong>#{{ selectedOrder()?.id }}</strong> de <strong>{{
        selectedOrder()?.customerName }}</strong>?</p>
    <p class="warning-text">Esta acción no se puede deshacer.</p>

    <div class="modal-actions">
      <button type="button" class="btn-secondary" (click)="closeModal()">Cancelar</button>
      <button type="button" class="btn-danger" (click)="confirmDelete()" [disabled]="loading()">
        @if (loading()) { Eliminando... } @else { Eliminar }
      </button>
    </div>
  </div>
  }
</app-modal>
