// order-frontend/order-react/src/orders/order-list/order-list.tsx
import { useEffect } from 'react'
import './order-list.css'
import type { Order } from '../../models/Order';
import { getOrdersAction } from '../actions/get-orders.action';
import { useAuthStore } from '../../login/store/auth.store';
import { useNavigate } from 'react-router-dom';
import { useOrderStore } from '../store/order.store';

export const OrderList = () => {

    const { isAuthenticated, setIsAuthenticated } = useAuthStore();
    const { orders, setOrders } = useOrderStore();

    const navigate = useNavigate();

    const handleLogout = () => {
        sessionStorage.removeItem('credentials');
        sessionStorage.removeItem('username');
        setIsAuthenticated(false);
        navigate('/login');
    }

    const navigateToOrderDetails = (orderId: number) => {
        navigate(`/details/${orderId}`);
    }

    const calculateTotal = (order: Order): number => {
        return order.items.reduce((total, item) => total + (item.quantity * item.unitPrice), 0);
    }

    useEffect(() => {
        if (!isAuthenticated) {
            navigate('/login');
            return;
        }
        getOrdersAction().then((orders) => {
            setOrders(orders);
        });
    }, [isAuthenticated]);

    return (
        <div className="order-list-container">
            <header className="header">
                <div className="header-content">
                    <h1>Lista de Pedidos</h1>
                    <div className="header-actions">
                        <div className="stream-indicator">
                            <span className="stream-dot"></span>
                            <span>Conectado en tiempo real</span>
                        </div>

                        <div className="user-info">
                            <span>Usuario: </span>
                            <button className="logout-button" onClick={handleLogout}>Cerrar Sesión</button>
                        </div>
                    </div>
                </div>
            </header>


            <div className="loading">
                <p>Cargando pedidos...</p>
            </div>

            <div className="orders-grid">
                {orders.length > 0 ? (
                    orders.map((order: Order) => (
                        <div className="order-card" onClick={() => navigateToOrderDetails(order.id)} key={order.id}>
                            <div className="order-header">
                                <h2>Pedido #{order.id}</h2>
                                <span className="order-date">{order.createdAt}</span>
                            </div>
                            <div className="order-customer">
                                <strong>Cliente:</strong> {order.customerName}
                            </div>
                            <div className="order-items">
                                <strong>Items:</strong> {order.items.length}
                            </div>
                            <div className="order-total">
                                <strong>Total:</strong> {calculateTotal(order)}
                            </div>
                        </div>
                    ))
                ) : (
                    <div className="empty">
                        <p>No hay pedidos disponibles</p>
                    </div>
                )
                }
            </div>

            <div className="error">
                <p></p>
                <button>Reintentar</button>
            </div>

        </div>

    )
}

export default OrderList;

// order-frontend/src/app/components/order-list/order-list.component.ts
import { Component, signal, inject, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { OrderService } from '../../services/order.service';
import { AuthService } from '../../services/auth.service';
import { Order } from '../../models/Order';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-order-list',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './order-list.component.html',
  styleUrl: './order-list.component.css'
})
export class OrderListComponent implements OnDestroy {
  private orderService = inject(OrderService);
  private authService = inject(AuthService);
  private streamSubscription?: Subscription;
  private reconnectTimeout?: ReturnType<typeof setTimeout>;
  private isDestroyed = false;
  private retryCount = 0;
  private readonly maxRetries = 5;

  // Signals 
  orders = signal<Order[]>([]);
  loading = signal<boolean>(true);
  error = signal<string | null>(null);
  isStreaming = signal<boolean>(false);

  constructor() {
    this.loadOrders();
    this.connectToStream();
  }

  ngOnDestroy(): void {
    this.isDestroyed = true;
    if (this.reconnectTimeout) {
      clearTimeout(this.reconnectTimeout);
    }
    this.disconnectFromStream();
  }

  loadOrders(): void {
    this.loading.set(true);
    this.error.set(null);

    this.orderService.getAllOrders().subscribe({
      next: (orders) => {
        this.orders.set(orders);
        this.loading.set(false);
      },
      error: (err) => {
        this.error.set('Error al cargar los pedidos');
        this.loading.set(false);
        console.error('Error loading orders:', err);
      }
    });
  }

  connectToStream(): void {
    this.isStreaming.set(true);
    this.streamSubscription = this.orderService.streamOrders().subscribe({
      next: (orders) => {
        this.orders.set(orders);
        this.loading.set(false);
        this.error.set(null);
        // Reset retry count on successful connection
        this.retryCount = 0;
      },
      error: (err) => {
        this.isStreaming.set(false);
        console.error('Stream error:', err);
        
        // Only retry if we haven't exceeded max retries
        if (this.retryCount < this.maxRetries && !this.isDestroyed) {
          this.retryCount++;
          this.error.set(`Error en la conexión en tiempo real (Intento ${this.retryCount}/${this.maxRetries})`);
          
          this.reconnectTimeout = setTimeout(() => {
            if (!this.isDestroyed) {
              this.connectToStream();
            }
          }, 5000);
        } else {
          // Max retries reached
          this.error.set('Error en la conexión en tiempo real. Se agotaron los intentos de reconexión.');
          this.isStreaming.set(false);
        }
      }
    });
  }

  disconnectFromStream(): void {
    if (this.streamSubscription) {
      this.streamSubscription.unsubscribe();
      this.isStreaming.set(false);
    }
  }

  formatDate(dateString: string): string {
    return new Date(dateString).toLocaleString('es-ES');
  }

  calculateTotal(order: Order): number {
    return order.items.reduce((total, item) => total + (item.quantity * item.unitPrice), 0);
  }

  logout(): void {
    this.authService.logout();
  }

  getUsername(): string | null {
    return this.authService.username();
  }
}


<div class="order-list-container">
  <header class="header">
    <div class="header-content">
      <h1>Lista de Pedidos</h1>
      <div class="header-actions">
        @if (isStreaming()) {
          <div class="stream-indicator">
            <span class="stream-dot"></span>
            <span>Conectado en tiempo real</span>
          </div>
        }
        @if (getUsername()) {
          <div class="user-info">
            <span>Usuario: {{ getUsername() }}</span>
            <button class="logout-button" (click)="logout()">Cerrar Sesión</button>
          </div>
        }
      </div>
    </div>
  </header>

  @if (loading()) {
    <div class="loading">
      <p>Cargando pedidos...</p>
    </div>
  } @else if (error()) {
    <div class="error">
      <p>{{ error() }}</p>
      <button (click)="loadOrders()">Reintentar</button>
    </div>
  } @else if (orders().length === 0) {
    <div class="empty">
      <p>No hay pedidos disponibles</p>
    </div>
  } @else {
    <div class="orders-grid">
      @for (order of orders(); track order.id) {
        <a [routerLink]="['/orders', order.id]" class="order-card">
          <div class="order-header">
            <h2>Pedido #{{ order.id }}</h2>
            <span class="order-date">{{ formatDate(order.createdAt) }}</span>
          </div>
          <div class="order-customer">
            <strong>Cliente:</strong> {{ order.customerName }}
          </div>
          <div class="order-items">
            <strong>Items:</strong> {{ order.items.length }}
          </div>
          <div class="order-total">
            <strong>Total:</strong> {{ calculateTotal(order) | number:'1.2-2' }} $
          </div>
        </a>
      }
    </div>
  }
</div>
